[[constraint]]
  name = "github.com/botopolis/bot"
  version = "0.4.0"

[[constraint]]
  name = "github.com/nlopes/slack"
  revision = "d86785d50d4be9c2e11cfbb0ed601f5dcb22899c"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"
