[[constraint]]
  name = "github.com/botopolis/bot"
  version = "0.4.2"

[[constraint]]
  name = "github.com/nlopes/slack"
  revision = "752f784a75e8b640f048a8a453466cca64c83a47"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"
